name: Gatling Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-gatling-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - index: 1
            commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.GetAllProductsOpen'
          - index: 2
            commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.PostAddProductOpen'
          - index: 3
            commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.PutUpdateProductOpen'
          - index: 4
            commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.DeleteProductOpen'
          - index: 5
            commands: 'mvn gatling:test -Dgatling.simulationClass=modeloCerrado.GetAllProductClosed'
          - index: 6
            commands: 'mvn gatling:test -Dgatling.simulationClass=modeloCerrado.PostAddProductClosed'
          - index: 7
            commands: 'mvn gatling:test -Dgatling.simulationClass=modeloCerrado.PutUpdateProductClosed'
          - index: 8
            commands: 'mvn gatling:test -Dgatling.simulationClass=modeloCerrado.DeleteProductClosed'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: 'mvn clean install -DskipTests'

      - name: Run Gatling Simulation
        run: ${{ matrix.commands }}

      - name: Generate Gatling Report
        run: ls -lh target/gatling

      - name: Upload Gatling Report as Artifact
        if: always ()
        uses: actions/upload-artifact@v4
        with:
           name: gatling-report-${{ matrix.index }}-${{ github.run_id }}
           path: target/gatling/*