name: Gatling Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-gatling-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        simulation:
          - mvn gatling:test -D"gatling.simulationClass=modeloAbierto.GetAllProductsAtOnceUsers"
          - mvn gatling:test -D"gatling.simulationClass=modeloAbierto.GetAllProductsConstantUsersDuring"
          - mvn gatling:test -D"gatling.simulationClass=modeloAbierto.GetAllProductsRampUsers.scala"
          - mvn gatling:test -D"gatling.simulationClass=modeloAbierto.PostAddProductAtOnceUsers"
          - mvn gatling:test -D"gatling.simulationClass=modeloAbierto.PostAddProductCombinado"


    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Install dependencies
        run: mvn install

      - name: Run Gatling Simulation
        run: mvn gatling:test -Dgatling.simulationClass=${{ matrix.simulation }}