name: Gatling Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-gatling-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.GetAllProductsAtOnceUsers'
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.GetAllProductsConstantUsersDuring'
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.GetAllProductsRampUsers.scala'
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.PostAddProductAtOnceUsers'
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.PostAddProductCombinado'


    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install

      - name: Run Gatling Simulation
        run: mvn gatling:test -Dgatling.simulationClass=${{ matrix.simulation }}