name: Gatling Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-gatling-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.GetAllProductsOpen'
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.PostAddProductOpen'
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.PutUpdateProductOpen'
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloAbierto.DeleteProductOpen'
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloCerrado.GetAllProductClosed'
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloCerrado.PostAddProductClosed'
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloCerrado.PutUpdateProductClosed'
          - commands: 'mvn gatling:test -Dgatling.simulationClass=modeloCerrado.DeleteProductClosed'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: 'mvn clean install -DskipTests'

      - name: Run Gatling Simulation
        run: ${{ matrix.commands }}